development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: simple_development
  pool: 5
  #
  host: localhost

  username: postgres_user
  password: pwpostgres

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: simple_test

  host: localhost

  username: postgres_user
  password: pwpostgres


production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: simple_production
